server:
  port: 8089
    
 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bms
    username: root
    password: 1135
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect 
  application:
    name: Department-Service 


 
         
  
#    
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#     defaultZone: http://localhost:8762/eureka/
#  instance:
#    hostname: localhost
    